# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bridge_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "bridge_service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14\x62ridge_service.proto\x12\ttongrobot\x1a\x11robot_state.proto\x1a\x11sensor_data.proto\x1a\x0e\x63ommands.proto"\x07\n\x05\x45mpty"*\n\rStreamRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x66ps\x18\x02 \x01(\x05">\n\x10TransformRequest\x12\x14\n\x0ctarget_frame\x18\x01 \x01(\t\x12\x14\n\x0csource_frame\x18\x02 \x01(\t"G\n\x0cTransformMsg\x12\x10\n\x08position\x18\x01 \x03(\x01\x12\x12\n\nquaternion\x18\x02 \x03(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\x01".\n\nCommandAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb0\x05\n\x0fTongRobotBridge\x12;\n\rGetRobotState\x12\x10.tongrobot.Empty\x1a\x18.tongrobot.RobotStateMsg\x12@\n\x10StreamRobotState\x12\x10.tongrobot.Empty\x1a\x18.tongrobot.RobotStateMsg0\x01\x12\x45\n\x0eGetCameraFrame\x12\x18.tongrobot.StreamRequest\x1a\x19.tongrobot.CameraFrameMsg\x12K\n\x12StreamCameraFrames\x12\x18.tongrobot.StreamRequest\x1a\x19.tongrobot.CameraFrameMsg0\x01\x12\x41\n\x0cGetLaserScan\x12\x18.tongrobot.StreamRequest\x1a\x17.tongrobot.LaserScanMsg\x12\x35\n\x06GetIMU\x12\x18.tongrobot.StreamRequest\x1a\x11.tongrobot.IMUMsg\x12J\n\x12SetVelocityCommand\x12\x1d.tongrobot.VelocityCommandMsg\x1a\x15.tongrobot.CommandAck\x12\x44\n\x0fSetJointCommand\x12\x1a.tongrobot.JointCommandMsg\x1a\x15.tongrobot.CommandAck\x12\x38\n\rEmergencyStop\x12\x10.tongrobot.Empty\x1a\x15.tongrobot.CommandAck\x12\x44\n\x0cGetTransform\x12\x1b.tongrobot.TransformRequest\x1a\x17.tongrobot.TransformMsgb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "bridge_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_EMPTY"]._serialized_start = 89
    _globals["_EMPTY"]._serialized_end = 96
    _globals["_STREAMREQUEST"]._serialized_start = 98
    _globals["_STREAMREQUEST"]._serialized_end = 140
    _globals["_TRANSFORMREQUEST"]._serialized_start = 142
    _globals["_TRANSFORMREQUEST"]._serialized_end = 204
    _globals["_TRANSFORMMSG"]._serialized_start = 206
    _globals["_TRANSFORMMSG"]._serialized_end = 277
    _globals["_COMMANDACK"]._serialized_start = 279
    _globals["_COMMANDACK"]._serialized_end = 325
    _globals["_TONGROBOTBRIDGE"]._serialized_start = 328
    _globals["_TONGROBOTBRIDGE"]._serialized_end = 1016
# @@protoc_insertion_point(module_scope)
