# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import bridge_service_pb2 as bridge__service__pb2
from . import commands_pb2 as commands__pb2
from . import robot_state_pb2 as robot__state__pb2
from . import sensor_data_pb2 as sensor__data__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in bridge_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class TongRobotBridgeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRobotState = channel.unary_unary(
            "/tongrobot.TongRobotBridge/GetRobotState",
            request_serializer=bridge__service__pb2.Empty.SerializeToString,
            response_deserializer=robot__state__pb2.RobotStateMsg.FromString,
            _registered_method=True,
        )
        self.StreamRobotState = channel.unary_stream(
            "/tongrobot.TongRobotBridge/StreamRobotState",
            request_serializer=bridge__service__pb2.Empty.SerializeToString,
            response_deserializer=robot__state__pb2.RobotStateMsg.FromString,
            _registered_method=True,
        )
        self.GetCameraFrame = channel.unary_unary(
            "/tongrobot.TongRobotBridge/GetCameraFrame",
            request_serializer=bridge__service__pb2.StreamRequest.SerializeToString,
            response_deserializer=sensor__data__pb2.CameraFrameMsg.FromString,
            _registered_method=True,
        )
        self.StreamCameraFrames = channel.unary_stream(
            "/tongrobot.TongRobotBridge/StreamCameraFrames",
            request_serializer=bridge__service__pb2.StreamRequest.SerializeToString,
            response_deserializer=sensor__data__pb2.CameraFrameMsg.FromString,
            _registered_method=True,
        )
        self.GetLaserScan = channel.unary_unary(
            "/tongrobot.TongRobotBridge/GetLaserScan",
            request_serializer=bridge__service__pb2.StreamRequest.SerializeToString,
            response_deserializer=sensor__data__pb2.LaserScanMsg.FromString,
            _registered_method=True,
        )
        self.GetIMU = channel.unary_unary(
            "/tongrobot.TongRobotBridge/GetIMU",
            request_serializer=bridge__service__pb2.StreamRequest.SerializeToString,
            response_deserializer=sensor__data__pb2.IMUMsg.FromString,
            _registered_method=True,
        )
        self.SetVelocityCommand = channel.unary_unary(
            "/tongrobot.TongRobotBridge/SetVelocityCommand",
            request_serializer=commands__pb2.VelocityCommandMsg.SerializeToString,
            response_deserializer=bridge__service__pb2.CommandAck.FromString,
            _registered_method=True,
        )
        self.SetJointCommand = channel.unary_unary(
            "/tongrobot.TongRobotBridge/SetJointCommand",
            request_serializer=commands__pb2.JointCommandMsg.SerializeToString,
            response_deserializer=bridge__service__pb2.CommandAck.FromString,
            _registered_method=True,
        )
        self.EmergencyStop = channel.unary_unary(
            "/tongrobot.TongRobotBridge/EmergencyStop",
            request_serializer=bridge__service__pb2.Empty.SerializeToString,
            response_deserializer=bridge__service__pb2.CommandAck.FromString,
            _registered_method=True,
        )
        self.GetTransform = channel.unary_unary(
            "/tongrobot.TongRobotBridge/GetTransform",
            request_serializer=bridge__service__pb2.TransformRequest.SerializeToString,
            response_deserializer=bridge__service__pb2.TransformMsg.FromString,
            _registered_method=True,
        )


class TongRobotBridgeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRobotState(self, request, context):
        """State"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamRobotState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetCameraFrame(self, request, context):
        """Sensors"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamCameraFrames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetLaserScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetIMU(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetVelocityCommand(self, request, context):
        """Commands"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetJointCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def EmergencyStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTransform(self, request, context):
        """TF"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TongRobotBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetRobotState": grpc.unary_unary_rpc_method_handler(
            servicer.GetRobotState,
            request_deserializer=bridge__service__pb2.Empty.FromString,
            response_serializer=robot__state__pb2.RobotStateMsg.SerializeToString,
        ),
        "StreamRobotState": grpc.unary_stream_rpc_method_handler(
            servicer.StreamRobotState,
            request_deserializer=bridge__service__pb2.Empty.FromString,
            response_serializer=robot__state__pb2.RobotStateMsg.SerializeToString,
        ),
        "GetCameraFrame": grpc.unary_unary_rpc_method_handler(
            servicer.GetCameraFrame,
            request_deserializer=bridge__service__pb2.StreamRequest.FromString,
            response_serializer=sensor__data__pb2.CameraFrameMsg.SerializeToString,
        ),
        "StreamCameraFrames": grpc.unary_stream_rpc_method_handler(
            servicer.StreamCameraFrames,
            request_deserializer=bridge__service__pb2.StreamRequest.FromString,
            response_serializer=sensor__data__pb2.CameraFrameMsg.SerializeToString,
        ),
        "GetLaserScan": grpc.unary_unary_rpc_method_handler(
            servicer.GetLaserScan,
            request_deserializer=bridge__service__pb2.StreamRequest.FromString,
            response_serializer=sensor__data__pb2.LaserScanMsg.SerializeToString,
        ),
        "GetIMU": grpc.unary_unary_rpc_method_handler(
            servicer.GetIMU,
            request_deserializer=bridge__service__pb2.StreamRequest.FromString,
            response_serializer=sensor__data__pb2.IMUMsg.SerializeToString,
        ),
        "SetVelocityCommand": grpc.unary_unary_rpc_method_handler(
            servicer.SetVelocityCommand,
            request_deserializer=commands__pb2.VelocityCommandMsg.FromString,
            response_serializer=bridge__service__pb2.CommandAck.SerializeToString,
        ),
        "SetJointCommand": grpc.unary_unary_rpc_method_handler(
            servicer.SetJointCommand,
            request_deserializer=commands__pb2.JointCommandMsg.FromString,
            response_serializer=bridge__service__pb2.CommandAck.SerializeToString,
        ),
        "EmergencyStop": grpc.unary_unary_rpc_method_handler(
            servicer.EmergencyStop,
            request_deserializer=bridge__service__pb2.Empty.FromString,
            response_serializer=bridge__service__pb2.CommandAck.SerializeToString,
        ),
        "GetTransform": grpc.unary_unary_rpc_method_handler(
            servicer.GetTransform,
            request_deserializer=bridge__service__pb2.TransformRequest.FromString,
            response_serializer=bridge__service__pb2.TransformMsg.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "tongrobot.TongRobotBridge", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "tongrobot.TongRobotBridge", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class TongRobotBridge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRobotState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tongrobot.TongRobotBridge/GetRobotState",
            bridge__service__pb2.Empty.SerializeToString,
            robot__state__pb2.RobotStateMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamRobotState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/tongrobot.TongRobotBridge/StreamRobotState",
            bridge__service__pb2.Empty.SerializeToString,
            robot__state__pb2.RobotStateMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetCameraFrame(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tongrobot.TongRobotBridge/GetCameraFrame",
            bridge__service__pb2.StreamRequest.SerializeToString,
            sensor__data__pb2.CameraFrameMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamCameraFrames(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/tongrobot.TongRobotBridge/StreamCameraFrames",
            bridge__service__pb2.StreamRequest.SerializeToString,
            sensor__data__pb2.CameraFrameMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetLaserScan(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tongrobot.TongRobotBridge/GetLaserScan",
            bridge__service__pb2.StreamRequest.SerializeToString,
            sensor__data__pb2.LaserScanMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetIMU(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tongrobot.TongRobotBridge/GetIMU",
            bridge__service__pb2.StreamRequest.SerializeToString,
            sensor__data__pb2.IMUMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SetVelocityCommand(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tongrobot.TongRobotBridge/SetVelocityCommand",
            commands__pb2.VelocityCommandMsg.SerializeToString,
            bridge__service__pb2.CommandAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SetJointCommand(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tongrobot.TongRobotBridge/SetJointCommand",
            commands__pb2.JointCommandMsg.SerializeToString,
            bridge__service__pb2.CommandAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def EmergencyStop(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tongrobot.TongRobotBridge/EmergencyStop",
            bridge__service__pb2.Empty.SerializeToString,
            bridge__service__pb2.CommandAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTransform(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tongrobot.TongRobotBridge/GetTransform",
            bridge__service__pb2.TransformRequest.SerializeToString,
            bridge__service__pb2.TransformMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
