# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robot_state.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "robot_state.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11robot_state.proto\x12\ttongrobot"Z\n\rJointStateMsg\x12\x11\n\tpositions\x18\x01 \x03(\x01\x12\x12\n\nvelocities\x18\x02 \x03(\x01\x12\x0f\n\x07\x65\x66\x66orts\x18\x03 \x03(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\x01"E\n\x0c\x42\x61seStateMsg\x12\x10\n\x08position\x18\x01 \x03(\x01\x12\x10\n\x08velocity\x18\x02 \x03(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\x01"G\n\x0fGripperStateMsg\x12\x10\n\x08position\x18\x01 \x01(\x01\x12\x0f\n\x07is_open\x18\x02 \x01(\x08\x12\x11\n\ttimestamp\x18\x03 \x01(\x01"\xdb\x02\n\rRobotStateMsg\x12\x30\n\x04\x61rms\x18\x01 \x03(\x0b\x32".tongrobot.RobotStateMsg.ArmsEntry\x12%\n\x04\x62\x61se\x18\x02 \x01(\x0b\x32\x17.tongrobot.BaseStateMsg\x12\x38\n\x08grippers\x18\x03 \x03(\x0b\x32&.tongrobot.RobotStateMsg.GrippersEntry\x12\x11\n\ttimestamp\x18\x04 \x01(\x01\x12\x10\n\x08has_base\x18\x05 \x01(\x08\x1a\x45\n\tArmsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.tongrobot.JointStateMsg:\x02\x38\x01\x1aK\n\rGrippersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.tongrobot.GripperStateMsg:\x02\x38\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "robot_state_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ROBOTSTATEMSG_ARMSENTRY"]._loaded_options = None
    _globals["_ROBOTSTATEMSG_ARMSENTRY"]._serialized_options = b"8\001"
    _globals["_ROBOTSTATEMSG_GRIPPERSENTRY"]._loaded_options = None
    _globals["_ROBOTSTATEMSG_GRIPPERSENTRY"]._serialized_options = b"8\001"
    _globals["_JOINTSTATEMSG"]._serialized_start = 32
    _globals["_JOINTSTATEMSG"]._serialized_end = 122
    _globals["_BASESTATEMSG"]._serialized_start = 124
    _globals["_BASESTATEMSG"]._serialized_end = 193
    _globals["_GRIPPERSTATEMSG"]._serialized_start = 195
    _globals["_GRIPPERSTATEMSG"]._serialized_end = 266
    _globals["_ROBOTSTATEMSG"]._serialized_start = 269
    _globals["_ROBOTSTATEMSG"]._serialized_end = 616
    _globals["_ROBOTSTATEMSG_ARMSENTRY"]._serialized_start = 470
    _globals["_ROBOTSTATEMSG_ARMSENTRY"]._serialized_end = 539
    _globals["_ROBOTSTATEMSG_GRIPPERSENTRY"]._serialized_start = 541
    _globals["_ROBOTSTATEMSG_GRIPPERSENTRY"]._serialized_end = 616
# @@protoc_insertion_point(module_scope)
