# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "sensor_data.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11sensor_data.proto\x12\ttongrobot"\x8b\x01\n\x0e\x43\x61meraFrameMsg\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x04 \x01(\x05\x12\x11\n\ttimestamp\x18\x05 \x01(\x01\x12\x10\n\x08\x65ncoding\x18\x06 \x01(\t\x12\x15\n\ris_compressed\x18\x07 \x01(\x08"p\n\x0cLaserScanMsg\x12\x0e\n\x06ranges\x18\x01 \x03(\x02\x12\x11\n\tangle_min\x18\x02 \x01(\x02\x12\x11\n\tangle_max\x18\x03 \x01(\x02\x12\x17\n\x0f\x61ngle_increment\x18\x04 \x01(\x02\x12\x11\n\ttimestamp\x18\x05 \x01(\x01"g\n\x06IMUMsg\x12\x13\n\x0borientation\x18\x01 \x03(\x01\x12\x18\n\x10\x61ngular_velocity\x18\x02 \x03(\x01\x12\x1b\n\x13linear_acceleration\x18\x03 \x03(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "sensor_data_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CAMERAFRAMEMSG"]._serialized_start = 33
    _globals["_CAMERAFRAMEMSG"]._serialized_end = 172
    _globals["_LASERSCANMSG"]._serialized_start = 174
    _globals["_LASERSCANMSG"]._serialized_end = 286
    _globals["_IMUMSG"]._serialized_start = 288
    _globals["_IMUMSG"]._serialized_end = 391
# @@protoc_insertion_point(module_scope)
